api_key: null
class_name: null
dataloader_num_workers: 1
exp_name: example
finetune_unet: true
logging_dir: null
mixed_precision: 'no'
moft_method: cayley
moft_nblocks: 32
moft_scale: true
output_dir: null
placeholder_token_concept: null
placeholder_token_style: null
pretrained_model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0
prompt_channel: 1024
resolution: 1024
revision: null
seed: 8
